// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentMat.Infrastructure.Data;

#nullable disable

namespace RentMat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618110526_UserCreatedAtDateTimeOffset")]
    partial class UserCreatedAtDateTimeOffset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentMat.Core.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.HasIndex("DeviceId", "StartDate", "EndDate");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_RentalBooking_EndAfterStart", "\"EndDate\" > \"StartDate\"");

                            t.HasCheckConstraint("CK_RentalBooking_TotalPrice_NonNegative", "\"TotalPrice\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            EndDate = new DateTimeOffset(new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartDate = new DateTimeOffset(new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Completed",
                            TotalPrice = 750m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 2,
                            EndDate = new DateTimeOffset(new DateTime(2026, 6, 22, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartDate = new DateTimeOffset(new DateTime(2026, 6, 20, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Created",
                            TotalPrice = 5760m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 3,
                            EndDate = new DateTimeOffset(new DateTime(2026, 6, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartDate = new DateTimeOffset(new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Active",
                            TotalPrice = 4800m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 2,
                            EndDate = new DateTimeOffset(new DateTime(2026, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StartDate = new DateTimeOffset(new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Cancelled",
                            TotalPrice = 960m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourRentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            HourRentPrice = 150m,
                            Name = "PlayStation 5 Pro",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            HourRentPrice = 120m,
                            Name = "Xbox Series X",
                            Status = "Rented"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            HourRentPrice = 200m,
                            Name = "Meta Quest 3 (128GB)",
                            Status = "Rented"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            HourRentPrice = 350m,
                            Name = "ASUS ROG (RTX 4090, i9)",
                            Status = "Maintenance"
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Консоли"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VR-Шлемы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Мощные ПК"
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 5000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dragonborn@tamriel.com",
                            HashedPassword = "hash",
                            Login = "Dovahkiin"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 15000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "geralt@kaermorhen.com",
                            HashedPassword = "hash",
                            Login = "Geralt"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 25000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "shepard@normandy.com",
                            HashedPassword = "hash",
                            Login = "Shepard"
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.Booking", b =>
                {
                    b.HasOne("RentMat.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentMat.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentMat.Core.Models.Device", b =>
                {
                    b.HasOne("RentMat.Core.Models.DeviceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
