// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentMat.Infrastructure.Data;

#nullable disable

namespace RentMat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentMat.Core.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourRentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            HourRentPrice = 150.00m,
                            Name = "PlayStation 5 Pro",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            HourRentPrice = 120.00m,
                            Name = "Xbox Series X",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            HourRentPrice = 200.00m,
                            Name = "Meta Quest 3 (128GB)",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            HourRentPrice = 350.00m,
                            Name = "ASUS ROG (RTX 4090, i9)",
                            Status = 2
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DeviceCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Консоли"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VR-Шлемы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Мощные ПК"
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 5000.00m,
                            CreatedAt = new DateTime(2007, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dragonborn@tamriel.com",
                            HashedPassword = "$2a$11$MX9xI7v09h4Lz6e6PZ7hCOgK8I.C2vS8iWx9wG1R1Wq8M2kM5G2t.",
                            Login = "Dovahkiin"
                        });
                });

            modelBuilder.Entity("RentMat.Core.Models.Device", b =>
                {
                    b.HasOne("RentMat.Core.Models.DeviceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
